/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeahlianSlugRouteImport } from './routes/keahlian.$slug'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeahlianSlugRoute = KeahlianSlugRouteImport.update({
  id: '/keahlian/$slug',
  path: '/keahlian/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keahlian/$slug': typeof KeahlianSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keahlian/$slug': typeof KeahlianSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keahlian/$slug': typeof KeahlianSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/keahlian/$slug' | '/skills/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keahlian/$slug' | '/skills/$slug'
  id: '__root__' | '/' | '/keahlian/$slug' | '/skills/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeahlianSlugRoute: typeof KeahlianSlugRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keahlian/$slug': {
      id: '/keahlian/$slug'
      path: '/keahlian/$slug'
      fullPath: '/keahlian/$slug'
      preLoaderRoute: typeof KeahlianSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeahlianSlugRoute: KeahlianSlugRoute,
  SkillsSlugRoute: SkillsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
